modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/MapperTV/embellishcraft_bop/issues"
[[mods]]
modId="embellishcraft_bop"
version="${file.jarVersion}"
displayName="EmbellishCraft BoP Addon"
#updateJSONURL="http://myurl.me/" #optional
displayURL="http://mapper.tv/embellishcraft/"
logoFile="embellishcraft_bop_logo.png"
credits="Thanks for Forge devs and modders that let their mods open-source."
authors="Mapper"
description='''EmbellishCraft BOP Addon is an Embellishcraft addon that adds Biomes O'Plenty wood variants to EmbellishCraft's furniture.'''

[[dependencies.embellishcraft_bop]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft_bop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
    
#[[dependencies.embellishcraft_bop]]
#    modId="mapperbase"
#    mandatory=true
#    versionRange="[1.18.1-4.0,)"
#    ordering="AFTER"
#    side="BOTH"
    
[[dependencies.embellishcraft_bop]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.18.1-15.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.embellishcraft_bop]]
    modId="embellishcraft"
    mandatory=true
    versionRange="[1.18.1-5.0,)"
    ordering="AFTER"
    side="BOTH"